mode:
 channle1 : 6 #切换模式通道
 channle2 : 4
 value1 : 1065 #模式通道1杆量
 value2 : 1933
 value3 : 1065 #通道2杆量
 value4 : 1499
 value5 : 1933
cam: #相机参数
 x_err : 3 #x轴相对误差
 y_err : -5 #y轴相对误差
 R: 0 #相机旋转角度

asd : 123.00
